###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [49]:
import numpy as np
a = np.array([[92,90,74],
    [6,63,93],
    [15,93,96],
    [70,60,48]])
a

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [6]:
np.sort(a)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [17]:
# ii. based on 2nd column

a[np.argsort(a[:,1])]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [32]:
# iii. based on row max- ascending

a[np.argsort(np.max(a, axis=1))[::-1]]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [50]:
# iv. based on elements value

np.sort(a, axis=None).reshape(4,3)


array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [98]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks


array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [99]:
# i. Add marks every student of an extra subject in the same array.
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)
marks = np.append(marks, extra_subject, axis=1)
marks


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [100]:
# ii.

rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)

marks = np.concatenate([marks, rec1, rec2], axis=0)
marks


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [101]:
# iii. Add extra column with sum of all subjects(5-subjects) marks

total = np.sum(marks, axis = 1).reshape(7,1)
marks = np.append(marks, total, axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [127]:
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

marks[np.argsort(marks[:,-1:],axis=0)[::-1]].reshape(7,6)

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [130]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.unique(arr, axis=0))
print(np.unique(arr, axis=1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [132]:
print(arr)
np.flip(arr)

[[1 2 3 3 1 1]
 [0 9 1 2 8 8]
 [1 2 3 8 8 8]
 [1 2 3 3 1 1]]


array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [138]:
a = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
X = 6
np.unique(np.where(a>X)[0])

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [159]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [160]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [161]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [162]:
np.delete(arr, [np.argmin(arr), np.argmax(arr)])

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [179]:
arr = np.arange(1000)
print(arr)
lim_arr = np.clip(arr, a_min=100, a_max=200)
print(lim_arr)
np.cumsum(np.sort(lim_arr))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

array([   100,    200,    300,    400,    500,    600,    700,    800,
          900,   1000,   1100,   1200,   1300,   1400,   1500,   1600,
         1700,   1800,   1900,   2000,   2100,   2200,   2300,   2400,
         2500,   2600,   2700,   2800,   2900,   3000,   3100,   3200,
         3300,   3400,   3500,   3600,   3700,   3800,   3900,   4000,
         4100,   4200,   4300,   4400,   4500,   4600,   4700,   4800,
         4900,   5000,   5100,   5200,   5300,   5400,   5500,   5600,
         5700,   5800,   5900,   6000,   6100,   6200,   6300,   6400,
         6500,   6600,   6700,   6800,   6900,   7000,   7100,   7200,
         7300,   7400,   7500,   7600,   7700,   7800,   7900,   8000,
         8100,   8200,   8300,   8400,   8500,   8600,   8700,   8800,
         8900,   9000,   9100,   9200,   9300,   9400,   9500,   9600,
         9700,   9800,   9900,  10000,  10100,  10201,  10303,  10406,
        10510,  10615,  10721,  10828,  10936,  11045,  11155,  11266,
      

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [183]:
a = np.random.random(100)
a_round = np.round_(a, decimals=3)
a_round

array([0.125, 0.919, 0.665, 0.292, 0.435, 0.179, 0.258, 0.434, 0.546,
       0.015, 0.381, 0.188, 0.663, 0.947, 0.542, 0.699, 0.188, 0.992,
       0.285, 0.808, 0.937, 0.465, 0.772, 0.733, 0.528, 0.787, 0.02 ,
       0.146, 0.703, 0.475, 0.325, 0.863, 0.485, 0.761, 0.433, 0.07 ,
       0.274, 0.703, 0.671, 0.299, 0.308, 0.507, 0.729, 0.057, 0.784,
       0.084, 0.527, 0.671, 0.056, 0.797, 0.553, 0.771, 0.701, 0.965,
       0.348, 0.034, 0.676, 0.238, 0.513, 0.576, 0.626, 0.556, 0.175,
       0.987, 0.838, 0.982, 0.953, 0.652, 0.987, 0.584, 0.444, 0.162,
       0.377, 0.965, 0.784, 0.936, 0.314, 0.144, 0.668, 0.162, 0.107,
       0.758, 0.524, 0.382, 0.014, 0.711, 0.403, 0.807, 0.723, 0.825,
       0.207, 0.973, 0.318, 0.726, 0.963, 0.724, 0.521, 0.3  , 0.205,
       0.263])

In [187]:
print(np.percentile(a_round,0))
print(np.min(a_round))

0.014
0.014


In [188]:
print(np.max(a_round))
np.percentile(a_round,100)

0.992


0.992

In [191]:
print(np.percentile(a_round,50))
print(np.percentile(a_round,51))
result = np.percentile(a_round,51)-np.percentile(a_round,50)
print("difference is --> ", np.round(result, decimals=3))

0.535
0.54396
difference is -->  0.009
